/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReceiverDashboardRouteImport } from './routes/receiver-dashboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostNeedRouteImport } from './routes/post-need'
import { Route as NeedsRouteImport } from './routes/needs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DonorDashboardRouteImport } from './routes/donor-dashboard'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiverDashboardRoute = ReceiverDashboardRouteImport.update({
  id: '/receiver-dashboard',
  path: '/receiver-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostNeedRoute = PostNeedRouteImport.update({
  id: '/post-need',
  path: '/post-need',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsRoute = NeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorDashboardRoute = DonorDashboardRouteImport.update({
  id: '/donor-dashboard',
  path: '/donor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/donate': typeof DonateRoute
  '/donor-dashboard': typeof DonorDashboardRoute
  '/login': typeof LoginRoute
  '/needs': typeof NeedsRoute
  '/post-need': typeof PostNeedRoute
  '/profile': typeof ProfileRoute
  '/receiver-dashboard': typeof ReceiverDashboardRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/donate': typeof DonateRoute
  '/donor-dashboard': typeof DonorDashboardRoute
  '/login': typeof LoginRoute
  '/needs': typeof NeedsRoute
  '/post-need': typeof PostNeedRoute
  '/profile': typeof ProfileRoute
  '/receiver-dashboard': typeof ReceiverDashboardRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/donate': typeof DonateRoute
  '/donor-dashboard': typeof DonorDashboardRoute
  '/login': typeof LoginRoute
  '/needs': typeof NeedsRoute
  '/post-need': typeof PostNeedRoute
  '/profile': typeof ProfileRoute
  '/receiver-dashboard': typeof ReceiverDashboardRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/donate'
    | '/donor-dashboard'
    | '/login'
    | '/needs'
    | '/post-need'
    | '/profile'
    | '/receiver-dashboard'
    | '/signup'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/donate'
    | '/donor-dashboard'
    | '/login'
    | '/needs'
    | '/post-need'
    | '/profile'
    | '/receiver-dashboard'
    | '/signup'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/donate'
    | '/donor-dashboard'
    | '/login'
    | '/needs'
    | '/post-need'
    | '/profile'
    | '/receiver-dashboard'
    | '/signup'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DonateRoute: typeof DonateRoute
  DonorDashboardRoute: typeof DonorDashboardRoute
  LoginRoute: typeof LoginRoute
  NeedsRoute: typeof NeedsRoute
  PostNeedRoute: typeof PostNeedRoute
  ProfileRoute: typeof ProfileRoute
  ReceiverDashboardRoute: typeof ReceiverDashboardRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiver-dashboard': {
      id: '/receiver-dashboard'
      path: '/receiver-dashboard'
      fullPath: '/receiver-dashboard'
      preLoaderRoute: typeof ReceiverDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-need': {
      id: '/post-need'
      path: '/post-need'
      fullPath: '/post-need'
      preLoaderRoute: typeof PostNeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs': {
      id: '/needs'
      path: '/needs'
      fullPath: '/needs'
      preLoaderRoute: typeof NeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor-dashboard': {
      id: '/donor-dashboard'
      path: '/donor-dashboard'
      fullPath: '/donor-dashboard'
      preLoaderRoute: typeof DonorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DonateRoute: DonateRoute,
  DonorDashboardRoute: DonorDashboardRoute,
  LoginRoute: LoginRoute,
  NeedsRoute: NeedsRoute,
  PostNeedRoute: PostNeedRoute,
  ProfileRoute: ProfileRoute,
  ReceiverDashboardRoute: ReceiverDashboardRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
